
spring:
  profiles: dev  
  datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://10.113.92.245:13306/PubTransDB
      username: pubtran
      password: PubTran12!@